
/*
# Filename:         controller.v
# File Description: RISC-V CPU controller generating all control signals for instruction execution
# Global variables: None
*/

module controller (
    input [6:0]  op,          // Opcode field of instruction (bits [6:0])
    input [2:0]  funct3,      // funct3 field (bits [14:12])
    input        funct7b5,    // Bit 30 of instruction (used for R-type add/sub)
    input        Zero,        // Zero flag from ALU (for branch decision)
    input        ALUR31,      // Flag from ALU or R-type instruction (specific usage depends on CPU design)
    input        ltu_flag,    // Unsigned comparison flag from ALU (less than unsigned)
    output [1:0] ResultSrc,   // Selects what goes back to register (ALU, Mem, PC+4, etc.)
    output       MemWrite,    // Enable memory write
    output       PCSrc,       // Selects next PC (sequential, branch, or jump)
    output       ALUSrc,      // Selects ALU input: register or immediate
    output       RegWrite,    // Enables register file write
    output       Jump,        // Indicates jump instruction
    output       Jalr,        // Indicates JALR instruction
    output [1:0] ImmSrc,      // Selects type of immediate (I, S, B, J, U)
    output [3:0] ALUControl   // ALU operation code (add, sub, and, or, etc.)
);

    // ==========================
    // Internal Signals
    // ==========================
    // ALUOp: Coarse ALU operation signal from main decoder, used by ALU decoder to determine exact operation
    wire [1:0] ALUOp;
    // Branch: Branch control signal generated by main decoder
    wire       Branch;

    // ==========================
    // Main Decoder
    // ==========================
    /*
    Purpose:
    ---
    Generates high-level control signals based on opcode (op) and other flags.
    Determines instruction type: branch, jump, memory access, ALU operation.
    Produces ALUOp to feed ALU decoder for detailed operation.
    */
    main_decoder md (
        op,            // Instruction opcode
        funct3,        // funct3 field
        Zero,          // ALU zero flag for conditional branch
        ALUR31,        // Special R-type instruction flag
        ltu_flag,      // Unsigned comparison flag
        ResultSrc,     // Output: selects data written to register file
        MemWrite,      // Output: enables memory write
        Branch,        // Output: branch control signal
        ALUSrc,        // Output: selects ALU input (register or immediate)
        RegWrite,      // Output: enables register write
        Jump,          // Output: jump instruction signal
        Jalr,          // Output: JALR instruction signal
        ImmSrc,        // Output: selects immediate type
        ALUOp          // Output: high-level ALU operation type
    );

    // ==========================
    // ALU Decoder
    // ==========================
    /*
    Purpose:
    ---
    Generates exact ALUControl signals using ALUOp, funct3, funct7b5.
    Maps coarse operation and instruction-specific fields to exact ALU function.
    Example: ALUOp=10 + funct3=000 + funct7b5=1 → SUB
    */
    alu_decoder ad (
        op[5],         // Sometimes distinguishes instruction type (e.g., LUI vs AUIPC)
        funct3,        // Instruction funct3 field
        funct7b5,      // Instruction bit 30 differentiates ADD/SUB, SRL/SRA
        ALUOp,         // Coarse ALU operation from main decoder
        ALUControl     // Output: exact ALU operation
    );

    // ==========================
    // PCSrc Logic
    // ==========================
    /*
    Purpose:
    ---
    Determines the next PC:
    - If branch instruction and ALU result is zero → take branch
    - If jump instruction → take jump
    */
    assign PCSrc = Branch | Jump;

endmodule
