/*
# Filename:         riscv_cpu.v
# File Description: Single-cycle RISC-V CPU implementation
# Global variables: None
*/

// riscv_cpu.v - single-cycle RISC-V CPU Processor

module riscv_cpu (
    input         clk, reset,             // Clock and reset signals
    output [31:0] PC,                     // Program Counter (current instruction address)
    input  [31:0] Instr,                  // Instruction fetched from instruction memory
    output        MemWrite,               // Memory write enable signal
    output [31:0] Mem_WrAddr, Mem_WrData, // Address and data for memory writes
    input  [31:0] ReadData,               // Data read from memory (load instruction)
    output [31:0] Result                  // Final ALU result (for debugging/observation)
);

// ==========================
// Control and Datapath Wires
// ==========================

// Control signals (generated by controller)
wire        ALUSrc;       // Selects between register value or immediate as ALU input
wire        RegWrite;     // Enables writing to register file
wire        Jump;         // Indicates jump instruction
wire        Zero;         // Zero flag from ALU (used in branches)
wire        Jalr;         // Indicates jump-and-link-register instruction
wire        ALUR31;       // Indicates ALU result should go to x31 (link register)
wire        ltu_flag;     // Unsigned comparison flag from ALU (less than unsigned)
wire [1:0]  ResultSrc;    // Selects what goes back to register file (ALU result, memory data, etc.)
wire [1:0]  ImmSrc;       // Selects immediate type (I, S, B, U, J)
wire [3:0]  ALUControl;   // Specifies ALU operation (ADD, SUB, AND, OR, etc.)

// ==========================
// Controller
// ==========================
// Purpose:
// ---
// Decodes instruction opcode, funct3, funct7, and ALU Zero flag to generate
// all control signals required for the datapath (ALU input, memory access,
// register write, branching, and jump signals).
controller  c   (
    Instr[6:0],    // Opcode (bits 6–0)
    Instr[14:12],  // funct3 (bits 14–12)
    Instr[30],     // funct7 (bit 30)
    Zero,          // ALU zero flag (for branch decision)
    ALUR31,        // Write to x31 if needed (for link)
    ltu_flag,      // Unsigned comparison result
    ResultSrc,     // Select result source for register writeback
    MemWrite,      // Memory write enable
    PCSrc,         // Select next PC (branch/jump/normal)
    ALUSrc,        // ALU input select
    RegWrite,      // Register file write enable
    Jump,          // Jump instruction signal
    Jalr,          // Jump-and-link-register signal
    ImmSrc,        // Immediate type select
    ALUControl     // ALU operation code
);

// ==========================
// Datapath
// ==========================
// Purpose:
// ---
// Implements the RISC-V datapath including Program Counter (PC),
// Register File, ALU, Immediate Generator, and Memory interface.
// Executes instructions using control signals generated by the controller.
datapath    dp  (
    clk, reset,       // Clock and reset
    ResultSrc, PCSrc, // Control for result selection and PC update
    ALUSrc, RegWrite, // ALU input select, Register write enable
    ImmSrc, ALUControl, // Immediate select, ALU control
    Jalr,             // Jump-and-link-register signal
    Zero,             // Zero flag output from ALU
    ALUR31,           // ALU result to link register flag
    ltu_flag,         // Unsigned comparison flag
    PC, Instr,        // Program Counter and current instruction
    Mem_WrAddr,       // Address to write in memory
    Mem_WrData,       // Data to write in memory
    ReadData,         // Data read from memory
    Result            // ALU result (for writeback/debug)
);

endmodule
