
/*
# Filename:         t1c_riscv_cpu.v
# File Description: Top-level Verilog module to integrate and test the RISC-V CPU core
# Global variables: None
*/

//
//====================================================
// t1c_riscv_cpu.v - Top Module to test RISC-V CPU
//====================================================
// This module connects the RISC-V CPU core with instruction
// and data memory modules. It provides optional external
// write capability for memory initialization and debugging.
//====================================================

module t1c_riscv_cpu (
    input         clk, reset,                 // Clock and reset inputs
    input         Ext_MemWrite,               // External memory write enable (used for testing/debugging)
    input  [31:0] Ext_WriteData,              // External write data for memory
    input  [31:0] Ext_DataAdr,                // External data address for memory
    output        MemWrite,                   // Final memory write enable (to data memory)
    output [31:0] WriteData,                  // Data going to memory
    output [31:0] DataAdr,                    // Address for data memory access
    output [31:0] ReadData,                   // Data read from data memory
    output [31:0] PC,                         // Program Counter
    output [31:0] Result                      // ALU result output (for debugging/observation)
);

    // -------------------------------------------------
    // Internal signal declarations
    // -------------------------------------------------

    wire [31:0] Instr;            // Instruction fetched from instruction memory
    wire [31:0] DataAdr_rv32;     // Data address generated by RISC-V CPU
    wire [31:0] WriteData_rv32;   // Data to be written to memory by CPU
    wire        MemWrite_rv32;    // Memory write control signal from CPU

    // ==========================
    // Instantiate CPU and Memories
    // ==========================

    // -------------------------------------------------
    // RISC-V CPU Core
    // -------------------------------------------------
    // This is the main processor module that fetches instructions,
    // executes them using ALU, and interacts with data memory.
    riscv_cpu rvcpu (
        clk, reset,
        PC, Instr,                // Instruction fetch interface
        MemWrite_rv32,            // Memory write control from CPU
        DataAdr_rv32,             // Data memory address from CPU
        WriteData_rv32,           // Data memory write data from CPU
        ReadData,                 // Data read from data memory into CPU
        Result                    // ALU result output from CPU
    );

    // -------------------------------------------------
    // Instruction Memory
    // -------------------------------------------------
    // Read-only memory used to store program instructions.
    // Instructions are indexed using the Program Counter (PC).
    instr_mem instrmem (
        PC,                       // Instruction address
        Instr                     // Instruction output to CPU
    );

    // -------------------------------------------------
    // Data Memory
    // -------------------------------------------------
    // Read/write memory used for data storage.
    // Connected to CPU or external interface for testing.
    data_mem datamem (
        clk, 
        MemWrite,                 // Memory write enable
        Instr[14:12],             // funct3 field for handling byte/halfword/word stores
        DataAdr,                  // Memory address
        WriteData,                // Data to be written
        ReadData                  // Data read output
    );

    // ==========================
    // Memory Access Control Logic
    // ==========================
    /*
    Purpose:
    ---
    This section selects whether memory access comes from
    the CPU or from an external source (for testbench/debug mode).
    When `reset=1` and `Ext_MemWrite=1`, external signals are used
    to load data memory (useful for preloading programs or test data).
    When `reset=0`, the CPU operates normally and drives memory signals.
    */

    assign MemWrite  = (Ext_MemWrite && reset) ? 1 : MemWrite_rv32;  // Select write control
    assign WriteData = (Ext_MemWrite && reset) ? Ext_WriteData : WriteData_rv32;  // Select write data
    assign DataAdr   = reset ? Ext_DataAdr : DataAdr_rv32;  // Select memory address source

endmodule


// ===========================================================
// Additional Notes:
// ===========================================================
// - Instruction memory is read-only; there is no direct write option.
//   For testbench purposes, instructions should be preloaded using a HEX file.
//
// - When `reset=1` and `Ext_MemWrite=1`, the external interface
//   allows preloading the data memory (e.g., loading initial program data).
//
// - When `reset=0`, the CPU takes over memory control,
//   and write operations occur normally during instruction execution (e.g., `sw` instruction).
// ===========================================================
